# Generated by Django 4.0.3 on 2022-03-31 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HZ', '0003_articl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articl',
            name='user_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HZ.user1'),
        ),
    ]
